spring:
  application:
    name: shopapp
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_LOCAL_PORT}/${MYSQL_DATABASE}?useTimezone=true&serverTimezone=America/Sao_Paulo
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    show-sql: true
    hibernate: 
      ddl-auto: update
    
shopapp:
  treasury:
    baseUrl: https://api.fiscaldata.treasury.gov/services
    timeout: 5000
