server:
  port: 8080

spring:
  application:
    name: shopapp
  datasource:
    url: jdbc:mysql://localhost:3306/shopcore?useTimezone=true&serverTimezone=America/Sao_Paulo
    username: root
    password: rootroot
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    show-sql: true
    hibernate: 
      ddl-auto: update

resilience4j.circuitbreaker:
  configs:
    default:
      failureRateThreshold: 50
      eventConsumerBufferSize: 10
      registerHealthIndicator: true
  instances:
    treasuryFiscalDataRates:
      registerHealthIndicator: true
      slidingWindowSize: 5
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: TIME_BASED
      minimumNumberOfCalls: 5
      waitDurationInOpenState: 45s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10


shopapp:
  treasury:
    baseUrl: https://api.fiscaldata.treasury.gov/services
    timeout: 5000