spring:
  application:
    name: shopapp
  datasource:
    url: jdbc:mysql://localhost:3306/shopcore?useTimezone=true&serverTimezone=America/Sao_Paulo
    username: root
    password: rootroot
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    show-sql: true
    hibernate: 
      ddl-auto: update
    
shopapp:
  treasury:
    baseUrl: https://api.fiscaldata.treasury.gov/services
    timeout: 5000
